{% set name = "pcne" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..
  # NOTE: When submitting to Bioconda, you'll typically replace 'path' with 'url' pointing
  # to a release tarball on GitHub and add a 'sha256' checksum. Example:
  # url: https://github.com/your_username/PlasmidCopynum/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: <checksum_of_the_tarball>

build:
  number: 0 # Increment if you rebuild the same version due to recipe changes
  # 'noarch: generic' means this package can run on any OS/architecture
  # because it only contains scripts (not compiled code).
  noarch: generic

requirements:
  host:
    - coreutils 
  run:
    - bash 
    - bwa >=0.7.19 
    - samtools >=1.20 
    - r-base >=4.4.2 
    - r-readr >=2.1.5 
    - r-dplyr >=1.1.4 

test:
  commands:
    - command -v pcne
    - pcne -h

about:
  home: https://github.com/riccabolla/PCNE 
  license: MIT 
  license_file: ../LICENSE 
  summary: 'Estimates plasmid copy number from assembled genome.'
  dev_url: https://github.com/riccabolla/PCNE 
extra:
  recipe-maintainers:
    - riccabolla 